#cloud-config

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io


users:
  - name: git_hub_user
    groups: [sudo, docker]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${deploy_ssh_key}
  - name: admin
    groups: [sudo, docker]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${admin_ssh_key}

runcmd:
  - mkdir -p /home/kittygram
  - chown git_hub_user:git_hub_user /home/kittygram
  - chmod 755 /home/kittygram
