name: Terraform Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy 

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: '1.11.3'
        
        - name: Check out infra directory only
          uses: actions/checkout@v3
          with:
            sparse-checkout: |
                infra
            sparse-checkout-cone-mode: false
        
        - name: Set up Service Account Key
          run: echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}" > key.json
    
        - name: Terraform Init
          run: terraform init
          env:
            TF_VAR_service_account_key_file: key.json
            TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
            TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}

        - name: Terraform Plan
          if: ${{ github.event.inputs.action == 'plan' }}
          run: terraform plan
    
        - name: Terraform Apply
          if: ${{ github.event.inputs.action == 'apply' }}
          run: terraform apply -auto-approve

        - name: Terraform Destroy
          working-directory: ./infra
          if: ${{ github.event.inputs.action == 'destroy' }}
          run: terraform destroy -auto-approve

        - name: Get Terraform Outputs
          working-directory: ./infra
          if: ${{ github.event.inputs.action == 'apply' }}
          run: |
            VM_IP=$(terraform output -raw public-ip-address-for-vm-1)
            echo "VM_IP=$VM_IP" >> $GITHUB_ENV
        
        - name: Send message in tg
          uses: appleboy/telegram-action@master
          if: ${{ github.event.inputs.action == 'apply' }}
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: >-
              VM создана с IP: $VM_IP!
              Автор: ${{ github.actor }}
              Комментарий: ${{ github.event.commits[0].message }}
              Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        